version: "2"
services:
  java:
    build:
      context: ../java
    ports:
      - "8080:80"
    depends_on:
      - jaeger
    environment:
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_SERVICE_NAME: workshop-java-app

  node:
    build:
      context: ../node
    ports:
      - "3000:80"
    depends_on:
      - jaeger
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      OTEL_SERVICE_NAME: "workshop-node-app"

  python:
    build:
      context: ../python
    ports:
      - "5000:80"
    depends_on:
      - jaeger
    environment:
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14268/api/traces"
      OTEL_TRACES_EXPORTER: jaeger_thrift
      OTEL_SERVICE_NAME: workshop-python-app

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # frontend
      - "14268:14268" # thrift ingest
      - "14250"       # proto ingest
